#!/usr/bin/env bash
# Run the watch app in the emery emulator for development.
#
# In order, this script:
#   1. Reaps leftover qemu-pebble / pypkjs processes from earlier runs
#      (pebble-tool leaks them on abrupt exit).
#   2. Bakes .env.local into src/pkjs/config_defaults.js so the app launches
#      pre-configured — the 2026 Pebble Core companion app's settings webview
#      is unreliable, and baked defaults sidestep needing it.
#   3. Builds with OWUI_DEBUG=1, which compiles the SELECT-in-IDLE
#      fake-dictation short-circuit (src/c/dictation.c) — the emulator has
#      no microphone, so canned utterances stand in for real dictation.
#   4. Boots the emulator and installs the app.
#   5. Watches src/ + package.json and rebuilds + reinstalls on every change.
#
# Ctrl-C stops the watch loop and reaps the emulator.
#
# Reads from .env.local: OWUI_HOST, OWUI_KEY (optional), OWUI_MODEL,
# EMU_PLATFORM (optional, default emery), OWUI_SYSTEM_PROMPT (optional),
# OWUI_FONT_SIZE (optional).
#
# This produces an OWUI_DEBUG build — emulator only. NEVER sideload it onto
# a real watch; the utterances are canned. Use scripts/release.sh for a
# publishable .pbw.

set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG_DEFAULTS=src/pkjs/config_defaults.js

command -v pebble >/dev/null 2>&1 || {
  echo "pebble-tool not on PATH. Install: uv tool install pebble-tool --python 3.13" >&2
  exit 1
}

if [ ! -f .env.local ]; then
  echo "Missing .env.local — create it with OWUI_HOST, OWUI_KEY, OWUI_MODEL." >&2
  exit 1
fi
set -a; . ./.env.local; set +a
: "${EMU_PLATFORM:=emery}"
: "${OWUI_HOST:?Set OWUI_HOST in .env.local}"
: "${OWUI_MODEL:?Set OWUI_MODEL in .env.local}"

reap() {
  # Specific patterns so this script (argv: "bash scripts/dev.sh") and the
  # config-baking python heredoc never match themselves.
  pkill -9 -f 'qemu-pebble ' 2>/dev/null || true
  pkill -9 -f 'python.*pypkjs' 2>/dev/null || true
}
trap reap EXIT INT TERM

if pgrep -f 'qemu-pebble ' >/dev/null 2>&1 || pgrep -f 'python.*pypkjs' >/dev/null 2>&1; then
  echo "=== reaping leftover qemu-pebble/pypkjs from a previous run ==="
  reap
  sleep 1
fi

echo "=== baking .env.local into $CONFIG_DEFAULTS ==="
python3 - "$CONFIG_DEFAULTS" <<'PYEOF'
import json, os, sys
cfg = {
    "serverUrl": os.environ["OWUI_HOST"],
    "apiKey":    os.environ.get("OWUI_KEY", ""),
    "model":     os.environ["OWUI_MODEL"],
}
if os.environ.get("OWUI_SYSTEM_PROMPT"):
    cfg["systemPrompt"] = os.environ["OWUI_SYSTEM_PROMPT"]
if os.environ.get("OWUI_FONT_SIZE"):
    cfg["fontSize"] = os.environ["OWUI_FONT_SIZE"]
js = ("// Generated by scripts/dev.sh from .env.local; do not edit by hand.\n"
      "// Gitignored. scripts/release.sh clears this for publishable builds.\n"
      "module.exports = " + json.dumps(cfg, indent=2) + ";\n")
open(sys.argv[1], "w").write(js)
print("  serverUrl = %s" % cfg["serverUrl"])
print("  model     = %s" % cfg["model"])
print("  apiKey    = %s" % ("<set>" if cfg["apiKey"] else "<blank>"))
PYEOF

export OWUI_DEBUG=1

echo "=== build + install (emulator: $EMU_PLATFORM) ==="
pebble build
pebble install --emulator "$EMU_PLATFORM"
echo "=== installed. Press SELECT in the emulator to dictate. ==="
echo "=== logs: pebble logs --emulator $EMU_PLATFORM  (run in another terminal) ==="

watch_changes() {
  if command -v fswatch >/dev/null 2>&1; then
    fswatch -o src/ package.json
  elif command -v inotifywait >/dev/null 2>&1; then
    while inotifywait -qqre modify,create,delete src/ package.json 2>/dev/null; do
      echo .
    done
  else
    echo "No fswatch/inotifywait found — polling src/ every 2s." >&2
    local stamp=/tmp/.owui-dev-stamp
    touch "$stamp"
    while :; do
      if find src/ package.json -newer "$stamp" 2>/dev/null | grep -q .; then
        echo .
        touch "$stamp"
      fi
      sleep 2
    done
  fi
}

echo "=== watching src/ + package.json (Ctrl-C to stop) ==="
watch_changes | while read -r _; do
  echo "=== change detected: rebuild + reinstall ==="
  if pebble build; then
    pebble install --emulator "$EMU_PLATFORM" || echo "(install failed)"
  else
    echo "(build failed; will retry on next change)"
  fi
done
