#!/usr/bin/env bash
# Bake .env.local values into src/pkjs/config_defaults.js so the watchapp
# launches pre-configured on first run. Useful because the 2026 Pebble
# companion app doesn't reliably surface a settings webview, leaving no way
# to enter an API key after install.
#
# Re-run before `pebble build` whenever .env.local changes. To revert to a
# blank-default build, just `git checkout src/pkjs/config_defaults.js` (or
# pass --clear).
#
# Reads:
#   OWUI_HOST              -> serverUrl
#   OWUI_KEY               -> apiKey
#   OWUI_MODEL             -> model
#   OWUI_SYSTEM_PROMPT     -> systemPrompt (optional)
#   OWUI_FONT_SIZE         -> fontSize (optional, 'medium' | 'large')

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=src/pkjs/config_defaults.js

if [ "${1:-}" = "--clear" ]; then
  cat > "$OUT" <<'EOF'
// Build-time overrides for the default config. Generated by
// scripts/inject-config-defaults.sh from .env.local. Committed as an empty
// object so release builds without that script still produce valid JS.
module.exports = {};
EOF
  echo "cleared $OUT"
  exit 0
fi

if [ ! -f .env.local ]; then
  echo "Missing .env.local — copy from .env.local.example and fill in." >&2
  exit 1
fi

# Inline env vars take precedence over .env.local; same convention as
# scripts/seed-emulator-config.sh.
for var in OWUI_HOST OWUI_KEY OWUI_MODEL OWUI_SYSTEM_PROMPT OWUI_FONT_SIZE; do
  if [ -n "${!var+x}" ]; then eval "EXT_${var}=\"\$${var}\""; eval "EXT_${var}_set=1"; fi
done

set -a; . ./.env.local; set +a

for var in OWUI_HOST OWUI_KEY OWUI_MODEL OWUI_SYSTEM_PROMPT OWUI_FONT_SIZE; do
  if [ -n "$(eval echo \${EXT_${var}_set:-})" ]; then
    eval "${var}=\"\$EXT_${var}\""
  fi
done

: "${OWUI_HOST:?Set OWUI_HOST in .env.local}"
: "${OWUI_MODEL:?Set OWUI_MODEL in .env.local}"

python3 - "$OUT" <<PYEOF
import json, sys, os, pathlib
out_path = sys.argv[1]
cfg = {
    "serverUrl":    os.environ["OWUI_HOST"],
    "apiKey":       os.environ.get("OWUI_KEY", ""),
    "model":        os.environ["OWUI_MODEL"],
}
if os.environ.get("OWUI_SYSTEM_PROMPT"):
    cfg["systemPrompt"] = os.environ["OWUI_SYSTEM_PROMPT"]
if os.environ.get("OWUI_FONT_SIZE"):
    cfg["fontSize"] = os.environ["OWUI_FONT_SIZE"]

js = (
    "// Generated by scripts/inject-config-defaults.sh; do not edit by hand.\n"
    "// Re-run that script (or pass --clear) to refresh.\n"
    "module.exports = " + json.dumps(cfg, indent=2) + ";\n"
)
pathlib.Path(out_path).write_text(js)
print(f"wrote {out_path}: serverUrl={cfg['serverUrl']} model={cfg['model']} apiKey={'<set>' if cfg.get('apiKey') else '<blank>'}")
PYEOF
